version = 1

exclude_patterns = [
    ".github/**",
    "etc/docker/**",
    "etc/build/**",
    "etc/propgen/**",
    "etc/sheetsaddon/**",
    "src/main/java/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "6"
  module_system = "commonjs"
  environment = ["browser"]