version = 1

exclude_patterns = [
    ".github/**",
    "etc/**",
    "src/java/**",
    "*/.xml",
    "*/*.min.js"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = ["browser"]